version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _offline
  timestamp: 1676023097
layout:
  top: {  }
  navigation: {  }
  /hero/: {  }
  /slideshow/: {  }
  /header/: {  }
  /above/: {  }
  /feature/: {  }
  /showcase/: {  }
  /utility/: {  }
  /container-main/:
    -
      -
        'sidebar 25': {  }
      -
        'mainbar 50':
          -
            - system-messages-8907
          -
            - system-content-2965
      -
        'aside 25': {  }
  /expanded/: {  }
  /extension/: {  }
  /bottom/: {  }
  /below/: {  }
  footer: {  }
  copyright: {  }
  offcanvas: {  }
structure:
  top:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  hero:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: 'jl-section jl-light'
  slideshow:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: ''
  header:
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  above:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  feature:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  showcase:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  utility:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
  mainbar:
    type: section
    subtype: main
    title: Main
    attributes:
      class: ''
      variations: ''
  aside:
    attributes:
      class: ''
      variations: ''
  container-main:
    attributes:
      boxed: ''
      maxwidth: ''
      class: jl-section
      extra: {  }
  expanded:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  extension:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  bottom:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  below:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  copyright:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
