name: 15
timestamp: 1677232174
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1676023097
positions:
  top-a: 'Top A'
  footer-a: 'Footer A'
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  hero: Hero
  above: Above
  feature: Feature
  showcase: Showcase
  utility: Utility
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  below: Below
  copyright: Copyright
  header: Header
  sidebar: Sidebar
  aside: Aside
  mainbar: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  position:
    position-position-4480: 'Top A'
    position-position-4856: 'Footer A'
  jlnavbar:
    jlnavbar-5122: 'JL Navbar'
  copyright:
    copyright-4385: Copyright
  branding:
    branding-7413: Branding
inherit:
  default:
    top: top
    navigation: navigation
    footer: footer
    copyright: copyright
    offcanvas: offcanvas
    position-position-4480: position-position-4652
    jlnavbar-5122: jlnavbar-2718
    position-position-4856: position-position-1616
    copyright-4385: copyright-6042
    branding-7413: branding-9377
