version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1676023097
layout:
  /top/:
    -
      - 'position-position-5496 50'
      - 'position-position-4652 50'
  /navigation/:
    -
      - jlnavbar-2718
  /hero/:
    -
      - position-position-5320
  /slideshow/:
    -
      - position-position-7292
  /header/:
    -
      - position-position-3605
  /above/:
    -
      - position-position-2010
  /feature/:
    -
      - position-position-7784
  /showcase/:
    -
      - position-position-8752
  /utility/:
    -
      - position-position-4593
  /container-main/:
    -
      -
        'sidebar 25':
          -
            - position-position-2532
      -
        'mainbar 50':
          -
            - system-messages-8907
          -
            - position-position-6716
          -
            - system-content-2965
      -
        'aside 25':
          -
            - position-position-1432
  /expanded/:
    -
      - position-position-4069
  /extension/:
    -
      - position-position-4868
  /bottom/:
    -
      - position-position-4901
  /below/:
    -
      - position-position-6202
  /footer/:
    -
      - position-position-1616
  /copyright/:
    -
      - 'copyright-6042 50'
      - 'branding-9377 50'
  offcanvas: {  }
structure:
  top:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: custom-top
      variations: 'nopaddingbottom nopaddingtop'
  navigation:
    type: section
    attributes:
      boxed: '2'
      maxwidth: ''
      class: ''
      variations: 'nomarginall nopaddingall'
  hero:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  slideshow:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: ''
  header:
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  above:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  feature:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  showcase:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  utility:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
  mainbar:
    type: section
    subtype: main
    title: Main
    attributes:
      class: ''
      variations: ''
  aside:
    attributes:
      class: ''
      variations: ''
  container-main:
    attributes:
      boxed: ''
      maxwidth: ''
      class: jl-section
      extra: {  }
  expanded:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  extension:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  bottom:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  below:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  footer:
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  copyright:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: 'nomargintop nomarginbottom'
  offcanvas:
    attributes:
      swipe: '0'
content:
  position-position-5496:
    title: 'Module Position'
    attributes:
      key: module-position
  position-position-4652:
    title: 'Top A'
    attributes:
      key: top-a
  jlnavbar-2718:
    title: 'JL Navbar'
    attributes:
      url: ''
      text: BaraMey
      image: 'gantry-media://xxx2.png'
      hoverExpand: '1'
      menu_visibility: m
      m_sticky: stickyonscroll
      mobile_logo: center
      mobile_menu_toggle: left
      menu_animation: offcanvas
      close_button: '1'
      module_id: ''
      navbar_style: extended
      logo_color: '#ffffff'
      mobile_text_color: '#ffffff'
      navbar_fontsize: 13px
      navbar_text_transform: uppercase
      dropdown_navbar_text_transform: capitalize
      layout: left
      sticky: stickyonscroll
      social_items:
        -
          social_icon: 'fab fa-linkedin-in'
          social_text: Linkedin
          social_title: ''
          social_link: '#'
          name: 'New item'
        -
          social_icon: 'fab fa-facebook-f'
          social_text: Facebook
          social_title: ''
          social_link: '#'
          name: 'New item'
        -
          social_icon: 'fab fa-twitter'
          social_text: Twitter
          social_title: ''
          social_link: '#'
          name: 'New item'
        -
          social_icon: 'fab fa-behance'
          social_text: Behance
          social_title: ''
          social_link: '#'
          name: 'New item'
      social_pos: header
      social_inverse: light
      container_maxwidth: default
      main_nav_margin: '1'
  position-position-5320:
    title: Hero
    attributes:
      enabled: 0
      key: breadcrumbs
  position-position-7292:
    title: Slideshow
    attributes:
      key: slideshow
    block:
      variations: 'nomarginall nopaddingall'
  position-position-3605:
    title: 'Header A'
    attributes:
      key: header-a
  position-position-2010:
    title: 'Above A'
    attributes:
      key: above-a
  position-position-7784:
    title: 'Feature A'
    attributes:
      key: feature-a
  position-position-8752:
    title: 'Showcase A'
    attributes:
      key: showcase-a
  position-position-4593:
    title: 'Utility A'
    attributes:
      key: utility-a
  position-position-2532:
    title: 'Sidebar A'
    attributes:
      key: sidebar-a
  position-position-6716:
    title: 'Mainbar A'
    attributes:
      key: mainbar-a
  position-position-1432:
    title: 'Aside A'
    attributes:
      key: aside-a
  position-position-4069:
    title: 'Expanded A'
    attributes:
      key: expanded-a
  position-position-4868:
    title: 'Extension A'
    attributes:
      key: extension-a
  position-position-4901:
    title: 'Bottom A'
    attributes:
      key: bottom-a
  position-position-6202:
    title: 'Below A'
    attributes:
      key: below-a
  position-position-1616:
    title: 'Footer A'
    attributes:
      key: footer-a
  copyright-6042:
    attributes:
      date:
        start: ''
        end: now
      owner: BaraMey
    block:
      variations: nomarginbottom
  branding-9377:
    attributes:
      content: 'Your food explorer'
    block:
      variations: nomargintop
