version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1643615697
layout:
  /top/: {  }
  /navigation/:
    -
      - jlnavbar-2718
  /hero/:
    -
      - position-position-5320
  /slideshow/:
    -
      - position-position-7292
  /header/:
    -
      - position-position-3605
  /above/:
    -
      - position-position-2010
  /feature/:
    -
      - position-position-7784
  /showcase/:
    -
      - position-position-8752
  /utility/:
    -
      - position-position-4593
  /container-main/:
    -
      -
        'sidebar 25':
          -
            - position-position-2532
      -
        'mainbar 50':
          -
            - system-messages-8907
          -
            - position-position-6716
          -
            - system-content-2965
      -
        'aside 25':
          -
            - position-position-1432
  /expanded/:
    -
      - position-position-4069
  /extension/:
    -
      - position-position-4868
  /bottom/:
    -
      - position-position-4901
  /below/:
    -
      - position-position-6202
  /footer/:
    -
      - jlfooterinfo-9592
  /copyright/:
    -
      - jldivider-6345
    -
      - 'copyright-6042 50'
      - 'branding-9377 50'
  offcanvas: {  }
structure:
  top:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: 'nopaddingbottom nopaddingtop jl-light'
  navigation:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: belgrade
      variations: 'nomarginall nopaddingall'
  hero:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  slideshow:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: ''
  header:
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: ''
  above:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: ''
  feature:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: ''
  showcase:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: ''
  utility:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: ''
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
  mainbar:
    type: section
    subtype: main
    title: Main
    attributes:
      class: ''
      variations: ''
  aside:
    attributes:
      class: ''
      variations: ''
  container-main:
    attributes:
      boxed: ''
      maxwidth: ''
      class: jl-section
      extra: {  }
  expanded:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: ''
  extension:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: ''
  bottom:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: ''
  below:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: ''
  footer:
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  copyright:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: ''
  offcanvas:
    attributes:
      swipe: '0'
content:
  jlnavbar-2718:
    title: 'JL Navbar'
    attributes:
      text: Finance
      hoverExpand: '1'
      menu_visibility: m
      m_sticky: stickyonscroll
      mobile_logo: center
      mobile_menu_toggle: left
      menu_animation: offcanvas
      close_button: '1'
      module_id: ''
      navbar_style: extended
      layout: right
      sticky: stickyonscroll
      search_pos: header
      search_style: modal
      icon_flip: '0'
      container_maxwidth: default
      main_nav_margin: '1'
  position-position-5320:
    title: Hero
    attributes:
      key: breadcrumbs
  position-position-7292:
    title: Slideshow
    attributes:
      key: slideshow
  position-position-3605:
    title: 'Header A'
    attributes:
      key: header-a
  position-position-2010:
    title: 'Above A'
    attributes:
      key: above-a
  position-position-7784:
    title: 'Feature A'
    attributes:
      key: feature-a
  position-position-8752:
    title: 'Showcase A'
    attributes:
      key: showcase-a
  position-position-4593:
    title: 'Utility A'
    attributes:
      key: utility-a
  position-position-2532:
    title: 'Sidebar A'
    attributes:
      key: sidebar-a
  position-position-6716:
    title: 'Mainbar A'
    attributes:
      key: mainbar-a
  position-position-1432:
    title: 'Aside A'
    attributes:
      key: aside-a
  position-position-4069:
    title: 'Expanded A'
    attributes:
      key: expanded-a
  position-position-4868:
    title: 'Extension A'
    attributes:
      key: extension-a
  position-position-4901:
    title: 'Bottom A'
    attributes:
      key: bottom-a
  position-position-6202:
    title: 'Below A'
    attributes:
      key: below-a
  jlfooterinfo-9592:
    title: 'JL Footer Info'
    attributes:
      image: ''
      image_alt: ''
      url: ''
      target: _self
      content: "<p>Finance offers an extensive range of professional services and a high degree of spe-cialization. We serves both private & public traded companies. We bring over 25 years of experience.</p>\n"
      html: ''
      twig: '0'
      filter: '0'
      module_id: ''
      chrome: ''
      items:
        -
          icon: 'fab fa-facebook-f'
          link: '#'
          link_target: _self
          name: 'New item'
        -
          icon: 'fab fa-twitter'
          link: '#'
          link_target: _self
          name: 'New item'
        -
          icon: 'fab fa-linkedin'
          link: '#'
          link_target: _self
          name: 'New item'
      image_width: ''
      image_height: ''
      social_style: button
      social_gutter: small
      social_margin_top: default
      content_margin_top: remove
      class: ''
      particle_title: ''
      particle_title_style: h3
      particle_title_decoration: none
      particle_title_align: inherit
      particle_predefined_color: default
      particle_title_color: ''
      particle_title_fontsize: ''
      particle_title_text_transform: ''
      particle_title_font_weight: ''
      particle_title_element: h3
      align: inherit
      breakpoint: always
      fallback: inherit
      g_maxwidth: inherit
      g_maxwidth_alignment: left
      g_maxwidth_breakpoint: always
      margin: inherit
      visibility: inherit
      animation: inherit
      animation_delay: ''
      animation_repeat: disabled
  jldivider-6345:
    title: 'JL Divider'
    attributes:
      divider_style: default
      divider_element: hr
      divider_align: inherit
      divider_breakpoint: always
      divider_fallback: inherit
      divider_border: '1'
      divider_color: 'rgba(255, 255, 255, 0.1)'
      class: ''
      particle_title: ''
      particle_title_style: h3
      particle_title_decoration: none
      particle_title_align: inherit
      particle_predefined_color: default
      particle_title_color: ''
      particle_title_fontsize: ''
      particle_title_text_transform: ''
      particle_title_font_weight: ''
      particle_title_element: h3
      align: inherit
      breakpoint: always
      fallback: inherit
      g_maxwidth: inherit
      g_maxwidth_alignment: left
      g_maxwidth_breakpoint: always
      margin: inherit
      visibility: inherit
      animation: inherit
      animation_delay: ''
      animation_repeat: disabled
      pa_horizontal_start: ''
      pa_horizontal_end: ''
      pa_vertical_start: ''
      pa_vertical_end: ''
      scale_start: ''
      scale_end: ''
      rotate_start: ''
      rotate_end: ''
      opacity_start: ''
      opacity_end: ''
      easing: ''
      pa_viewport: ''
      pa_z_index: '0'
      pa_breakpoint: always
    block:
      variations: 'nomarginleft nopaddingleft nomarginright nopaddingright nomarginbottom nopaddingbottom'
  copyright-6042:
    attributes:
      owner: 'Finance Consulting <a href="https://joomlead.com/" target="_blank">Joomla 4 Template</a>'
    block:
      variations: nopaddingtop
  branding-9377:
    block:
      variations: nopaddingtop
